### ISSUE TITLE
SyntaxError On Rakefile During 'docker-compose up'

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-docker#25]
### Environment
macOS 10.11.6, Docker for Mac 18.03.0-ce-mac60 (23751)

### Error
I receive the following error when running docker-compose up. I'm wondering if Ruby isn't 2.3+ and things are halting on the Safe Navigation Operator.

```
Step 19/24 : RUN         cd avalon &&               mkdir -p tmp/pids &&               bundle exec whenever -w -f config/docker_schedule.rb &&               bundle exec rake assets:precompile &&               cp config/controlled_vocabulary.yml.example config/controlled_vocabulary.yml &&               cd ..
 ---> Running in a9f85f9b25d0
[write] crontab file written
rake aborted!
SyntaxError: /home/app/avalon/lib/tasks/avalon.rake:47: syntax error, unexpected '.'
... ENV['namespace'] || Settings&.fedora&.namespace || 'avalon'
...                               ^
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/railties-4.2.9/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/railties-4.2.9/lib/rails/engine.rb:658:in `each'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/railties-4.2.9/lib/rails/engine.rb:658:in `run_tasks_blocks'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/railties-4.2.9/lib/rails/application.rb:452:in `run_tasks_blocks'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/railties-4.2.9/lib/rails/engine.rb:453:in `load_tasks'
/home/app/avalon/Rakefile:24:in `<top (required)>'
/home/app/avalon/vendor/gems/ruby/2.2.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.2.9@global/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.9@global/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.2.9@global/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.9@global/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.9@global/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
ERROR: Service 'avalon' failed to build: The command '/bin/sh -c cd avalon &&               mkdir -p tmp/pids &&               bundle exec whenever -w -f config/docker_schedule.rb &&               bundle exec rake assets:precompile &&               cp config/controlled_vocabulary.yml.example config/controlled_vocabulary.yml &&               cd ..' returned a non-zero code: 1
```

**Comment by phuongdh** [comment]
Looks like you have an older image for Avalon. I will tag Avalon with 6.4 so Docker is forced to download/build the new one.

**Comment by joncameron** [comment]
Thanks @phuongdh !

**Comment by cjcolvar** [comment]
@phuongdh @joncameron can we move this to done?

**Comment by joncameron** [comment]
@cjcolvar @phuongdh Yes! This is stale. Closing...
